apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aditya-demo-app
  namespace: argocd-devops-demo
spec:
  project: default
  source:
    repoURL: https://github.com/Kothari-Aditya/devops-ia-argo-cd-demo.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
